set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)

message(STATUS "VCPKG_ROOT_DIR:${VCPKG_ROOT_DIR}")
message(STATUS "PACKAGES_DIR:${PACKAGES_DIR}")
message(STATUS "BUILDTREES_DIR:${BUILDTREES_DIR}")
message(STATUS "_VCPKG_INSTALLED_DIR:${_VCPKG_INSTALLED_DIR}")
message(STATUS "DOWNLOADS:${DOWNLOADS}")
message(STATUS "VCPKG_MANIFEST_INSTALL:${VCPKG_MANIFEST_INSTALL}")
message(STATUS "Parameters:")